config/routes.rb
Rails.application.routes.draw do
  root 'main#dashboard'

  resources :apps, param: :app_name, only: %i{ index create destroy } do
    post :rename, on: :member
  end
  resources :config, param: :app_name
  resources :containers, param: :app_name
  resources :plugins, param: :plugin_name do
    member do
      patch ":state", action: :toggle_status, as: :toggle_status
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :error, :info, :warning

  private

  def ssh_connect
    Net::SSH.start(ENV["SSH_HOST"], ENV["SSH_USER"], password: ENV["SSH_PASS"]) do |ssh|
      yield ssh
    end
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    @output = []
    ssh_connect do |ssh|
     result = ssh.exec!('dokku apps:list')
     result.split("\n").each_with_index do |app, i|
       next if i == 0
       @output << app
     end
    end
  end

  def create
    app_name = params[:app_name]

    ssh_connect do |ssh|
      @output = ssh.exec!("dokku apps:create #{app_name}")
    end

    if @output&.match(/Creating #{app_name}... done/)
      render json: :ok
    else
      render json: :error, status: :unprocessable_entity
    end
  end

  def destroy
    app_name = params[:app_name]

    ssh_connect do |ssh|
      @output = ssh.exec!("dokku --force apps:destroy #{app_name}")
    end

    if @output&.match(/Destroying #{app_name}/)
      redirect_to apps_path, success: "App #{app_name} successfully deleted"
    else
      redirect_to apps_path, error: "App #{app_name} could not be deleted"
    end
  end

  def rename
    old_app_name = params[:old_app_name]
    new_app_name = params[:new_app_name]

    ssh_connect do |ssh|
      @output = ssh.exec!("dokku apps:rename #{old_app_name} #{new_app_name}")
    end

    if @output[/Renaming #{old_app_name} to #{new_app_name}... done/]
      render json: :ok
    else
      render json: :error, status: :unprocessable_entity
    end
  end
end

app/controllers/config_controller.rb
class ConfigController < ApplicationController
  before_action :set_app_name

  def show
    @output = []
    ssh_connect do |ssh|
     result = ssh.exec!("dokku config #{@app_name}")
     result.split("\n").each_with_index do |config, i|
       next if i == 0
       key, value = config.split(":", 2).map(&:strip)
       @output << [key, value] unless key.blank?
     end
    end
  end

  def destroy
    config_key = params[:config_key]

    @output = []
    ssh_connect do |ssh|
     @output = ssh.exec!("dokku config:unset --no-restart #{@app_name} #{config_key}")
    end

    if @output[/-----> Unsetting #{config_key}/]
      render json: :ok
    else
      render json: :error, status: :unprocessable_entity
    end
  end

  private

  def set_app_name
    @app_name = params[:app_name]
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  def index
    @output = []
    ssh_connect do |ssh|
     result = ssh.exec!('dokku ls')
     result.split("\n").each_with_index do |app, i|
       next if i == 0
       @output << app.split(" ").flatten
     end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def dashboard
    ssh_connect do |ssh|
      @cpu = ssh.exec!('cat /proc/cpuinfo | grep processor').split("\n").last.match(/processor\t:(\S*) (.*)/)[2].to_i + 1
      @memory = ssh.exec!('cat /proc/meminfo | grep MemTotal:').match(/^MemTotal:(\S*) (.*)/)[2].to_i * 1024
      @docker_version = ssh.exec!('docker --version').match(/^Docker version(\S*) (.*)/)[2]
      @dokku_version = ssh.exec!('dokku version')
    end
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  def index
    @output = []
    ssh_connect do |ssh|
     result = ssh.exec!('dokku plugin:list')
     result.split("\n").each_with_index do |app, i|
      if i == 0
        @plugin_version = app
        next
      end
       attributes = app.split(" ", 4).flatten
       @output << OpenStruct.new(name: attributes[0], version: attributes[1], status: attributes[2], description: attributes[3])
     end
    end
  end

  def toggle_status
    plugin_name = params[:plugin_name]
    state = params[:state]

    @output = []
    ssh_connect do |ssh|
      @output = ssh.exec!("sudo dokku plugin:#{state} #{plugin_name}") 
    end

    if @output[/-----> Plugin #{plugin_name} #{state}d/]
      render json: :ok
    else
      render json: :error, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(*controller_names)
    controller_names.each do |controller_name|
      if params[:controller] == controller_name
        return "active"
      end
    end
    nil
  end

  def is_active_action(*action_names)
    action_names.each do |action_name|
      if params[:action] == action_name
        return "active"
      end
    end
    nil
  end
  
  def flash_class(type)
    case type.to_sym
    when :error, :failure, :danger     then 'danger'
    when :info                         then 'info'
    when :notice, :success             then 'success'
    when :alert, :warning              then 'warning'
    else                               type.to_s
    end
  end
end

app/views/apps/index.html.erb
<h1 class="page-header">Your apps</h1>

<button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#myModal">
  <%= fa_icon "fw plus", text: "Add" %>
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create a new app</h4>
      </div>
      <div class="modal-body">
        <div class="alert hide"></div>
        <input type="text" name="app_name" id="app_name" class="form-control" placeholder="App name">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-success" id="create-app">Create</button>
      </div>
    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @output.each do |app| %>
        <tr>
          <td>
            <%= content_tag :span, app %>
            <%= link_to fa_icon("fw lg pencil"), "#", data: { app: app, state: "read" } %>
          </td>
          <td>
            <%= link_to fa_icon("remove"), app_path(app_name: app), class: "destroy-app btn btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this app?" } %>
            <div class="btn-group">
              <%= link_to fa_icon("cog"), config_path(app), class: "btn btn-sm btn-default" %>
            </div>
          </td>
        </tr>
      <% end %>

      <% unless @output.any? %>
        <tr>
          <td colspan="2"><em>You currently have no apps to display.</em></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/config/show.html.erb
<h1 class="page-header">Config: <%= @app_name %></h1>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Key</th>
        <th>Value</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @output.each do |config| %>
        <tr>
          <td><%= config[0] %></td>
          <td><%= config[1] %></td>
          <td><%= link_to fa_icon("remove"), config_path(app_name: @app_name, config_key: config[0]), class: "destroy-config btn btn-sm btn-danger", remote: true, method: :delete, data: { confirm: "Are you sure you want to delete this config var?" } %></td>
        </tr>
      <% end %>

      <% unless @output.any? %>
        <tr><td colspan="3">No config vars to display.</td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/containers/index.html.erb
<h1 class="page-header">Your containers</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Proc</th>
        <th>ID</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @output.each do |app| %>
        <tr>
          <td><%= app[0] %></td>
          <td><%= app[1] %></td>
          <td><%= app[2] %></td>
          <td><%= content_tag :span, app[3].humanize.upcase, class: "label label-#{ app[3] == "running" ? "success" : "danger" }" %></td>
        </tr>
      <% end %>

      <% unless @output.any? %>
        <tr>
          <td colspan="2"><em>You currently have no active procs to display.</em></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.select{|k,v| %w{error failure danger info notice success alert warning}.include?(k)}.each do |type, msg| %>
    <div class="alert alert-<%= flash_class(type) %> alert-dismissible m-t-sm m-b-sm" data-alert="true">
      <% unless flash[:important] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <% end %>
      <% if msg.is_a? Array %>
        <% msg.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% else %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <%= Date.today.year %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Dokku GUI</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if is_active_controller('main') && is_active_action('dashboard') %>">
          <%= link_to "Dashboard", root_path %>
        </li>
        <li class="<%= "active" if is_active_controller('apps') %>">
          <%= link_to "Apps", apps_path %>
        </li>
        <li class="<%= "active" if is_active_controller('containers') %>">
          <%= link_to "Containers", containers_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-sidebar">
  <li class="<%= "active" if is_active_controller('main') && is_active_action('dashboard') %>">
    <%= link_to fa_icon("fw dashboard", text: "Dashboard"), root_path %>
  </li>
  <li class="<%= "active" if is_active_controller('apps', 'config') %>">
    <%= link_to fa_icon("fw rocket", text: "Apps"), apps_path %>
  </li>
  <li class="<%= "active" if is_active_controller('containers') %>">
    <%= link_to fa_icon("fw server", text: "Containers"), containers_path %>
  </li>
  <li class="<%= "active" if is_active_controller('plugins') %>">
    <%= link_to fa_icon("fw plug", text: "Plugins"), plugins_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DokkuGui</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render "layouts/navigation" %>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= render "layouts/flash_messages" %>

          <%= yield %>

          <%= render "layouts/footer" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/main/dashboard.html.erb
<h3>CPU</h3>
<%= pluralize @cpu, "Core" %>

<h3>RAM</h3>
<%= number_to_human_size @memory %>

<h3>Docker version</h3>
<%= @docker_version %>

<h3>Dokku version</h3>
<%= @dokku_version %>

app/views/main/list.html.erb
<h1 class="page-header">Running processes</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Proc</th>
        <th>ID</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @output.each do |app| %>
        <tr>
          <td><%= app[0] %></td>
          <td><%= app[1] %></td>
          <td><%= app[2] %></td>
          <td><%= content_tag :span, app[3], class: "label label-#{ app[3] == "running" ? "success" : "danger" }" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/plugins/index.html.erb
<h1 class="page-header">Plugins</h1>

<div class="row">
  <div class="col-md-12"> 
    <div class="well well-sm pull-right">
      <%= @plugin_version %>
    </div>
  </div>
</div>

<% @output.group_by {|p| p.description[/^dokku core/] }.reverse_each do |group, plugins| %>
  <h4><%= group.present? ? "Dokku Core" : "Community (Yours)" %></h4>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <% unless group.present? %>
            <th></th>
          <% end %>
          <th>Name</th>
          <th>Version</th>
          <th>Status</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% plugins.each do |plugin| %>
          <tr>
            <% unless group.present? %>
              <td>
                <% if plugin.status == "enabled" %>
                  <%= link_to fa_icon("lg toggle-on"), toggle_status_plugin_path(plugin.name, "disable"), remote: true, method: :patch, class: "toggle-plugin" %>
                <% else %>
                  <%= link_to fa_icon("lg toggle-off"), toggle_status_plugin_path(plugin.name, "enable"), remote: true, method: :patch, class: "toggle-plugin" %>
                <% end %>
              </td>
            <% end %>
            <td><%= plugin.name %></td>
            <td><%= plugin.version %></td>
            <td><%= content_tag :span, plugin.status.humanize.upcase, class: "label label-#{ plugin.status == "enabled" ? "success" : "danger" }" %></td>
            <td><%= plugin.description %></td>
          </tr>
        <% end %>

        <% unless plugins.any? %>
          <tr>
            <td colspan="5"><em>You currently have no plugins to display.</em></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <hr>
<% end %>